### ISSUE TITLE
1.1

### ISSUE THREAD

**Issue by hultberg** [hultberg/vdu-theme#2]
Next release point. Look at the following:
- [x] #1 - Projectlist header
- [x] #4 - Add travis builds
- [ ] #8 - New quadcore logo
- [ ] Add GlobeLAN logo
